// Code generated by entc, DO NOT EDIT.

package ent

import (
	"LifeDocs/ent/comments"
	"LifeDocs/ent/experience"
	"LifeDocs/ent/predicate"
	"LifeDocs/ent/user"
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CommentsUpdate is the builder for updating Comments entities.
type CommentsUpdate struct {
	config
	hooks    []Hook
	mutation *CommentsMutation
}

// Where appends a list predicates to the CommentsUpdate builder.
func (cu *CommentsUpdate) Where(ps ...predicate.Comments) *CommentsUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUUID sets the "uuid" field.
func (cu *CommentsUpdate) SetUUID(u uuid.UUID) *CommentsUpdate {
	cu.mutation.SetUUID(u)
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CommentsUpdate) SetCreatedAt(t time.Time) *CommentsUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CommentsUpdate) SetNillableCreatedAt(t *time.Time) *CommentsUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetComment sets the "comment" field.
func (cu *CommentsUpdate) SetComment(s string) *CommentsUpdate {
	cu.mutation.SetComment(s)
	return cu
}

// SetLikes sets the "likes" field.
func (cu *CommentsUpdate) SetLikes(i int) *CommentsUpdate {
	cu.mutation.ResetLikes()
	cu.mutation.SetLikes(i)
	return cu
}

// AddLikes adds i to the "likes" field.
func (cu *CommentsUpdate) AddLikes(i int) *CommentsUpdate {
	cu.mutation.AddLikes(i)
	return cu
}

// SetPostsID sets the "posts" edge to the Experience entity by ID.
func (cu *CommentsUpdate) SetPostsID(id int) *CommentsUpdate {
	cu.mutation.SetPostsID(id)
	return cu
}

// SetNillablePostsID sets the "posts" edge to the Experience entity by ID if the given value is not nil.
func (cu *CommentsUpdate) SetNillablePostsID(id *int) *CommentsUpdate {
	if id != nil {
		cu = cu.SetPostsID(*id)
	}
	return cu
}

// SetPosts sets the "posts" edge to the Experience entity.
func (cu *CommentsUpdate) SetPosts(e *Experience) *CommentsUpdate {
	return cu.SetPostsID(e.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cu *CommentsUpdate) SetUserID(id int) *CommentsUpdate {
	cu.mutation.SetUserID(id)
	return cu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (cu *CommentsUpdate) SetNillableUserID(id *int) *CommentsUpdate {
	if id != nil {
		cu = cu.SetUserID(*id)
	}
	return cu
}

// SetUser sets the "user" edge to the User entity.
func (cu *CommentsUpdate) SetUser(u *User) *CommentsUpdate {
	return cu.SetUserID(u.ID)
}

// Mutation returns the CommentsMutation object of the builder.
func (cu *CommentsUpdate) Mutation() *CommentsMutation {
	return cu.mutation
}

// ClearPosts clears the "posts" edge to the Experience entity.
func (cu *CommentsUpdate) ClearPosts() *CommentsUpdate {
	cu.mutation.ClearPosts()
	return cu
}

// ClearUser clears the "user" edge to the User entity.
func (cu *CommentsUpdate) ClearUser() *CommentsUpdate {
	cu.mutation.ClearUser()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommentsUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommentsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommentsUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommentsUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommentsUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CommentsUpdate) check() error {
	if v, ok := cu.mutation.Comment(); ok {
		if err := comments.CommentValidator(v); err != nil {
			return &ValidationError{Name: "comment", err: fmt.Errorf("ent: validator failed for field \"comment\": %w", err)}
		}
	}
	if v, ok := cu.mutation.Likes(); ok {
		if err := comments.LikesValidator(v); err != nil {
			return &ValidationError{Name: "likes", err: fmt.Errorf("ent: validator failed for field \"likes\": %w", err)}
		}
	}
	return nil
}

func (cu *CommentsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   comments.Table,
			Columns: comments.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: comments.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UUID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: comments.FieldUUID,
		})
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: comments.FieldCreatedAt,
		})
	}
	if value, ok := cu.mutation.Comment(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: comments.FieldComment,
		})
	}
	if value, ok := cu.mutation.Likes(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: comments.FieldLikes,
		})
	}
	if value, ok := cu.mutation.AddedLikes(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: comments.FieldLikes,
		})
	}
	if cu.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.PostsTable,
			Columns: []string{comments.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: experience.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.PostsTable,
			Columns: []string{comments.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: experience.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.UserTable,
			Columns: []string{comments.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.UserTable,
			Columns: []string{comments.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comments.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CommentsUpdateOne is the builder for updating a single Comments entity.
type CommentsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentsMutation
}

// SetUUID sets the "uuid" field.
func (cuo *CommentsUpdateOne) SetUUID(u uuid.UUID) *CommentsUpdateOne {
	cuo.mutation.SetUUID(u)
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CommentsUpdateOne) SetCreatedAt(t time.Time) *CommentsUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CommentsUpdateOne) SetNillableCreatedAt(t *time.Time) *CommentsUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetComment sets the "comment" field.
func (cuo *CommentsUpdateOne) SetComment(s string) *CommentsUpdateOne {
	cuo.mutation.SetComment(s)
	return cuo
}

// SetLikes sets the "likes" field.
func (cuo *CommentsUpdateOne) SetLikes(i int) *CommentsUpdateOne {
	cuo.mutation.ResetLikes()
	cuo.mutation.SetLikes(i)
	return cuo
}

// AddLikes adds i to the "likes" field.
func (cuo *CommentsUpdateOne) AddLikes(i int) *CommentsUpdateOne {
	cuo.mutation.AddLikes(i)
	return cuo
}

// SetPostsID sets the "posts" edge to the Experience entity by ID.
func (cuo *CommentsUpdateOne) SetPostsID(id int) *CommentsUpdateOne {
	cuo.mutation.SetPostsID(id)
	return cuo
}

// SetNillablePostsID sets the "posts" edge to the Experience entity by ID if the given value is not nil.
func (cuo *CommentsUpdateOne) SetNillablePostsID(id *int) *CommentsUpdateOne {
	if id != nil {
		cuo = cuo.SetPostsID(*id)
	}
	return cuo
}

// SetPosts sets the "posts" edge to the Experience entity.
func (cuo *CommentsUpdateOne) SetPosts(e *Experience) *CommentsUpdateOne {
	return cuo.SetPostsID(e.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cuo *CommentsUpdateOne) SetUserID(id int) *CommentsUpdateOne {
	cuo.mutation.SetUserID(id)
	return cuo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (cuo *CommentsUpdateOne) SetNillableUserID(id *int) *CommentsUpdateOne {
	if id != nil {
		cuo = cuo.SetUserID(*id)
	}
	return cuo
}

// SetUser sets the "user" edge to the User entity.
func (cuo *CommentsUpdateOne) SetUser(u *User) *CommentsUpdateOne {
	return cuo.SetUserID(u.ID)
}

// Mutation returns the CommentsMutation object of the builder.
func (cuo *CommentsUpdateOne) Mutation() *CommentsMutation {
	return cuo.mutation
}

// ClearPosts clears the "posts" edge to the Experience entity.
func (cuo *CommentsUpdateOne) ClearPosts() *CommentsUpdateOne {
	cuo.mutation.ClearPosts()
	return cuo
}

// ClearUser clears the "user" edge to the User entity.
func (cuo *CommentsUpdateOne) ClearUser() *CommentsUpdateOne {
	cuo.mutation.ClearUser()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CommentsUpdateOne) Select(field string, fields ...string) *CommentsUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Comments entity.
func (cuo *CommentsUpdateOne) Save(ctx context.Context) (*Comments, error) {
	var (
		err  error
		node *Comments
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommentsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommentsUpdateOne) SaveX(ctx context.Context) *Comments {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommentsUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommentsUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CommentsUpdateOne) check() error {
	if v, ok := cuo.mutation.Comment(); ok {
		if err := comments.CommentValidator(v); err != nil {
			return &ValidationError{Name: "comment", err: fmt.Errorf("ent: validator failed for field \"comment\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.Likes(); ok {
		if err := comments.LikesValidator(v); err != nil {
			return &ValidationError{Name: "likes", err: fmt.Errorf("ent: validator failed for field \"likes\": %w", err)}
		}
	}
	return nil
}

func (cuo *CommentsUpdateOne) sqlSave(ctx context.Context) (_node *Comments, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   comments.Table,
			Columns: comments.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: comments.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Comments.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comments.FieldID)
		for _, f := range fields {
			if !comments.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comments.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UUID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: comments.FieldUUID,
		})
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: comments.FieldCreatedAt,
		})
	}
	if value, ok := cuo.mutation.Comment(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: comments.FieldComment,
		})
	}
	if value, ok := cuo.mutation.Likes(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: comments.FieldLikes,
		})
	}
	if value, ok := cuo.mutation.AddedLikes(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: comments.FieldLikes,
		})
	}
	if cuo.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.PostsTable,
			Columns: []string{comments.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: experience.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.PostsTable,
			Columns: []string{comments.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: experience.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.UserTable,
			Columns: []string{comments.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comments.UserTable,
			Columns: []string{comments.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Comments{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comments.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
