// Code generated by entc, DO NOT EDIT.

package ent

import (
	"LifeDocs/ent/comments"
	"LifeDocs/ent/experience"
	"LifeDocs/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ExperienceCreate is the builder for creating a Experience entity.
type ExperienceCreate struct {
	config
	mutation *ExperienceMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (ec *ExperienceCreate) SetUUID(u uuid.UUID) *ExperienceCreate {
	ec.mutation.SetUUID(u)
	return ec
}

// SetCreatedAt sets the "created_at" field.
func (ec *ExperienceCreate) SetCreatedAt(t time.Time) *ExperienceCreate {
	ec.mutation.SetCreatedAt(t)
	return ec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ec *ExperienceCreate) SetNillableCreatedAt(t *time.Time) *ExperienceCreate {
	if t != nil {
		ec.SetCreatedAt(*t)
	}
	return ec
}

// SetTitle sets the "title" field.
func (ec *ExperienceCreate) SetTitle(s string) *ExperienceCreate {
	ec.mutation.SetTitle(s)
	return ec
}

// SetContent sets the "content" field.
func (ec *ExperienceCreate) SetContent(s string) *ExperienceCreate {
	ec.mutation.SetContent(s)
	return ec
}

// SetViews sets the "views" field.
func (ec *ExperienceCreate) SetViews(i int) *ExperienceCreate {
	ec.mutation.SetViews(i)
	return ec
}

// SetLikes sets the "likes" field.
func (ec *ExperienceCreate) SetLikes(i int) *ExperienceCreate {
	ec.mutation.SetLikes(i)
	return ec
}

// AddCommentIDs adds the "comments" edge to the Comments entity by IDs.
func (ec *ExperienceCreate) AddCommentIDs(ids ...int) *ExperienceCreate {
	ec.mutation.AddCommentIDs(ids...)
	return ec
}

// AddComments adds the "comments" edges to the Comments entity.
func (ec *ExperienceCreate) AddComments(c ...*Comments) *ExperienceCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ec.AddCommentIDs(ids...)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ec *ExperienceCreate) SetUserID(id int) *ExperienceCreate {
	ec.mutation.SetUserID(id)
	return ec
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (ec *ExperienceCreate) SetNillableUserID(id *int) *ExperienceCreate {
	if id != nil {
		ec = ec.SetUserID(*id)
	}
	return ec
}

// SetUser sets the "user" edge to the User entity.
func (ec *ExperienceCreate) SetUser(u *User) *ExperienceCreate {
	return ec.SetUserID(u.ID)
}

// Mutation returns the ExperienceMutation object of the builder.
func (ec *ExperienceCreate) Mutation() *ExperienceMutation {
	return ec.mutation
}

// Save creates the Experience in the database.
func (ec *ExperienceCreate) Save(ctx context.Context) (*Experience, error) {
	var (
		err  error
		node *Experience
	)
	ec.defaults()
	if len(ec.hooks) == 0 {
		if err = ec.check(); err != nil {
			return nil, err
		}
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ExperienceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ec.check(); err != nil {
				return nil, err
			}
			ec.mutation = mutation
			if node, err = ec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			if ec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *ExperienceCreate) SaveX(ctx context.Context) *Experience {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *ExperienceCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *ExperienceCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *ExperienceCreate) defaults() {
	if _, ok := ec.mutation.UUID(); !ok {
		v := experience.DefaultUUID()
		ec.mutation.SetUUID(v)
	}
	if _, ok := ec.mutation.CreatedAt(); !ok {
		v := experience.DefaultCreatedAt()
		ec.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *ExperienceCreate) check() error {
	if _, ok := ec.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "uuid"`)}
	}
	if _, ok := ec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := ec.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "title"`)}
	}
	if v, ok := ec.mutation.Title(); ok {
		if err := experience.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "title": %w`, err)}
		}
	}
	if _, ok := ec.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "content"`)}
	}
	if v, ok := ec.mutation.Content(); ok {
		if err := experience.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "content": %w`, err)}
		}
	}
	if _, ok := ec.mutation.Views(); !ok {
		return &ValidationError{Name: "views", err: errors.New(`ent: missing required field "views"`)}
	}
	if v, ok := ec.mutation.Views(); ok {
		if err := experience.ViewsValidator(v); err != nil {
			return &ValidationError{Name: "views", err: fmt.Errorf(`ent: validator failed for field "views": %w`, err)}
		}
	}
	if _, ok := ec.mutation.Likes(); !ok {
		return &ValidationError{Name: "likes", err: errors.New(`ent: missing required field "likes"`)}
	}
	if v, ok := ec.mutation.Likes(); ok {
		if err := experience.LikesValidator(v); err != nil {
			return &ValidationError{Name: "likes", err: fmt.Errorf(`ent: validator failed for field "likes": %w`, err)}
		}
	}
	return nil
}

func (ec *ExperienceCreate) sqlSave(ctx context.Context) (*Experience, error) {
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ec *ExperienceCreate) createSpec() (*Experience, *sqlgraph.CreateSpec) {
	var (
		_node = &Experience{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: experience.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: experience.FieldID,
			},
		}
	)
	if value, ok := ec.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: experience.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := ec.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: experience.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := ec.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: experience.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := ec.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: experience.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := ec.mutation.Views(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: experience.FieldViews,
		})
		_node.Views = value
	}
	if value, ok := ec.mutation.Likes(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: experience.FieldLikes,
		})
		_node.Likes = value
	}
	if nodes := ec.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.CommentsTable,
			Columns: []string{experience.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: comments.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_posts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExperienceCreateBulk is the builder for creating many Experience entities in bulk.
type ExperienceCreateBulk struct {
	config
	builders []*ExperienceCreate
}

// Save creates the Experience entities in the database.
func (ecb *ExperienceCreateBulk) Save(ctx context.Context) ([]*Experience, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Experience, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExperienceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *ExperienceCreateBulk) SaveX(ctx context.Context) []*Experience {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *ExperienceCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *ExperienceCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
