// Code generated by entc, DO NOT EDIT.

package ent

import (
	"LifeDocs/ent/tags"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Tags is the model entity for the Tags schema.
type Tags struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Tag holds the value of the "tag" field.
	Tag string `json:"tag,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tags) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case tags.FieldID:
			values[i] = new(sql.NullInt64)
		case tags.FieldTag:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Tags", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tags fields.
func (t *Tags) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tags.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case tags.FieldTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag", values[i])
			} else if value.Valid {
				t.Tag = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Tags.
// Note that you need to call Tags.Unwrap() before calling this method if this Tags
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Tags) Update() *TagsUpdateOne {
	return (&TagsClient{config: t.config}).UpdateOne(t)
}

// Unwrap unwraps the Tags entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Tags) Unwrap() *Tags {
	tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tags is not a transactional entity")
	}
	t.config.driver = tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Tags) String() string {
	var builder strings.Builder
	builder.WriteString("Tags(")
	builder.WriteString(fmt.Sprintf("id=%v", t.ID))
	builder.WriteString(", tag=")
	builder.WriteString(t.Tag)
	builder.WriteByte(')')
	return builder.String()
}

// TagsSlice is a parsable slice of Tags.
type TagsSlice []*Tags

func (t TagsSlice) config(cfg config) {
	for _i := range t {
		t[_i].config = cfg
	}
}
