// Code generated by entc, DO NOT EDIT.

package tags

const (
	// Label holds the string label denoting the tags type in the database.
	Label = "tags"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTag holds the string denoting the tag field in the database.
	FieldTag = "tag"
	// Table holds the table name of the tags in the database.
	Table = "tags"
)

// Columns holds all SQL columns for tags fields.
var Columns = []string{
	FieldID,
	FieldTag,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TagValidator is a validator for the "tag" field. It is called by the builders before save.
	TagValidator func(string) error
)
