// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comments is the predicate function for comments builders.
type Comments func(*sql.Selector)

// Experience is the predicate function for experience builders.
type Experience func(*sql.Selector)

// Tags is the predicate function for tags builders.
type Tags func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
